spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lyh?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wdy740103
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.lyh: info
  file:
    path: log/lyh-pro.log

server:
  port: 8081
